[package]
name = "ipfs-cxx"
description = "IPFS trustless blocks verification"
version = "0.0.1"
edition = "2023"
publish = false

[dependencies]
thiserror=1.0.38
libipld=0.16.0
libipld-core=0.16.0
libipld-cbor=0.16.0

[lib]
name = "ipfs_cxx"
crate-type = ["rlib"]
